name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Test SSH connection
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo 'SSH connection is successful!'"

    - name: Deploy to VM
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          echo "Pull latest Docker image"
          docker pull your-dockerhub-username/artemis-backend-docker:latest

          echo "Stop existing container"
          docker stop artemis-backend-container || true
          docker rm artemis-backend-container || true

          echo "Run new container"
          docker run -d -p 3000:3000 --name artemis-backend-container \
            -v /home/nrizkynugraha/ARTEMIS-Backend/.env:/app/.env \
            -v /home/nrizkynugraha/ARTEMIS-Backend/gcs-key.json:/app/gcs-key.json \
            your-dockerhub-username/artemis-backend-docker:latest

          echo "Deployment done!"
        EOF
